name: Build Signed APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # ✅ GENERA EL KEYSTORE DIRECTAMENTE EN EL WORKFLOW (SIN SECRETOS)
    - name: Generate keystore
      run: |
        keytool -genkeypair \
          -alias joyacontrol \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -keystore app/joyacontrol.keystore \
          -storepass 123456 \
          -keypass 123456 \
          -dname "CN=Rafael Pérez, OU=Taller de Joyería, O=Taller de Joyería, L=Córdoba, ST=Córdoba, C=ES" \
          -storetype PKCS12

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Release APK
      env:
        KEYSTORE_PASSWORD: "123456"
        KEY_PASSWORD: "123456"
        KEY_ALIAS: "joyacontrol"
      run: ./gradlew assembleRelease --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
