    - name: Build Release APK with Gradle 8.0 (FORCED)
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        # Verificar que NO existe ./gradlew
        if [ -f "./gradlew" ]; then
          echo "ERROR: ./gradlew still exists! Deleting it..."
          rm ./gradlew
        fi
        # Usar solo 'gradle' (instalado por gradle-build-action)
        gradle --version
        gradle assembleRelease --stacktrace
